version: 2
jobs:
  build:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm install -g lerna
      - run: lerna bootstrap
      - run: lerna run build
      - run: lerna run test
      - run: lerna exec --scope foo -- sh -c '"curl -fsSL https://codecov.io/bash | bash /dev/stdin -Z -F $LERNA_PACKAGE_NAME -f coverage/clover.xml"'
